---
title: "The Bernoulli Distribution"
author: "Gabriel J. Odom"
date: last-modified
format:
  html:
    embed-resources: true
    code-fold: true
knitr:
  opts_chunk:        ########## set global options ############
    collapse: true   # keep code from blocks together (if shown)
    echo: true       # show code
    message: true    # show messages
    warning: true    # show warnings
    error: true      # show error messages
    comment: ""      # don't show ## with printed output
    dpi: 100         # image resolution (typically 300 for publication)
    fig-width: 6.5   # figure width
    fig-height: 4.0  # figure height
    R.options:    
      digits: 3    # round to three digits
editor: source
---

```{r, tidyverse-tidymodels}
#| echo: false

library(conflicted)
suppressPackageStartupMessages(library(tidymodels))
tidymodels_prefer()
suppressPackageStartupMessages(library(tidyverse))

# suppress "`summarise()` has grouped output by " messages
options(dplyr.summarise.inform = FALSE)
```



## Deriving the Distribution


-------------------------------------------------------------------------------



## Example Random Samples

```{r, random-sample}
set.seed(20150516)

x <- rbinom(n = 100, size = 1, prob = 0.5)
samples_ls <- list(
  n5   = x[1:5],
  n15  = x[1:15],
  n30  = x[1:30],
  n100 = x
)

rm(x)
```

```{r}
#| label: random-sample-hist
#| fig-show: "hold"

par(mfrow = c(2, 2))

hist(samples_ls$n5)
hist(samples_ls$n15)
hist(samples_ls$n30)
hist(samples_ls$n100)

par(mfrow = c(1, 1))
```


-------------------------------------------------------------------------------



## Show that this is a Distribution


-------------------------------------------------------------------------------



## Derive the Moment Generating Function

> **The Riemman-Stieljes Integral**
> 
> Let $f$ be a bounded function on the interval $\mathcal{S} = [a, b] \subset \mathbb{R}$, and let $G$ be a monotone increasing (but not necessarily continuous) function on $\mathcal{S}$. The Riemman-Stieljes integral of $f$ with respect to $G$ is denoted as
$$
\text{R-S}(f, G) \equiv \int_{x \in \mathcal{S}} f(x) \text{d}G(x).
$$
If $G$ is continuous $\forall x \in \mathcal{S}$, then this integral simplifies to 
$$
\int_{x \in \mathcal{S}} f(x) \text{d}G(x) = \int_{x \in \mathcal{S}} f(x) g^{\prime}(x).
$$
If, however, there exists $k < m < \infty$ points of discontinuity for $G$ on $\mathcal{S}$, we define an $m$-partition of $\mathcal{S}$ as $[a = y_0, y_1), [y_1, y_2), \ldots, [y_{m - 2}, y_{m - 1}), [y_{m - 1}, b = y_m]$, where the $k$ points of discontinuity are included in the sequence $\{y_1, y_2, \ldots, y_{m - 1}\}$. Then, this integral simplifies to 
$$
\int_{x \in \mathcal{S}} f(x) \text{d}G(x) = \sum\limits_{i = 1}^m f(x)\left[ G(y_i) - G(y_{i - 1}) \right].
$$


-------------------------------------------------------------------------------



## Method of Moments Estimators


-------------------------------------------------------------------------------



## Maximum Likelihood Estimators


-------------------------------------------------------------------------------



## Exercises


