---
title: "The Normal Distribution"
author: "Gabriel J. Odom"
date: last-modified
format:
  html:
    embed-resources: false
    code-fold: true
knitr:
  opts_chunk:        ########## set global options ############
    collapse: true   # keep code from blocks together (if shown)
    echo: true       # show code
    message: true    # show messages
    warning: true    # show warnings
    error: true      # show error messages
    comment: ""      # don't show ## with printed output
    dpi: 100         # image resolution (typically 300 for publication)
    fig-width: 6.5   # figure width
    fig-height: 4.0  # figure height
    R.options:    
      digits: 3    # round to three digits
editor: source
---

```{r, tidyverse-tidymodels}
#| echo: false

library(conflicted)
suppressPackageStartupMessages(library(tidymodels))
tidymodels_prefer()
suppressPackageStartupMessages(library(tidyverse))

# suppress "`summarise()` has grouped output by " messages
options(dplyr.summarise.inform = FALSE)
```



## Deriving the Distribution


</br>



## Example Random Samples

```{r, random-sample}
set.seed(20150516)

xStandard <- rnorm(n = 1000, mean = 0, sd = 1)
samplesStd_ls <- list(
  n5    = xStandard[1:5],
  n30   = xStandard[1:30],
  n60   = xStandard[1:60],
  n1000 = xStandard
)

xShift <- rnorm(n = 1000, mean = 1, sd = 2)
samplesShifted_ls <- list(
  n5    = xShift[1:5],
  n30   = xShift[1:30],
  n60   = xShift[1:60],
  n1000 = xShift
)

range_num <- range(c(xStandard, xShift))

rm(xSymm, xSkew)
```

```{r}
#| label: shared-density-plotting-function
PlotSharedDensity <- function(x, range_x, bandwidth = "nrd0") {
  
  xDens_ls <- density(x, bw = bandwidth)
  xHist_ls <- hist(x, plot = FALSE)
  yLargest_num <- max(max(xDens_ls$y), max(xHist_ls$density))
  
  hist(
    x, prob = TRUE,
    xlim = range_x, ylim = c(0, yLargest_num)
  )
  lines(xDens_ls, col = 4, lwd = 2)
  
}
```


```{r}
#| label: random-sample-hist-symm
#| fig-show: "hold"

par(mfrow = c(2, 2))

PlotSharedDensity(
  x = samplesStd_ls$n5, range_x = range_num
)
PlotSharedDensity(
  x = samplesStd_ls$n30, range_x = range_num
)
PlotSharedDensity(
  x = samplesStd_ls$n60, range_x = range_num
)
PlotSharedDensity(
  x = samplesStd_ls$n1000, range_x = range_num
)

par(mfrow = c(1, 1))

# , bandwidth = 0.005
```

```{r}
#| label: random-sample-hist-diffuse
#| fig-show: "hold"

par(mfrow = c(2, 2))

PlotSharedDensity(
  x = samplesShifted_ls$n5, range_x = range_num
)
PlotSharedDensity(
  x = samplesShifted_ls$n30, range_x = range_num
)
PlotSharedDensity(
  x = samplesShifted_ls$n60, range_x = range_num
)
PlotSharedDensity(
  x = samplesShifted_ls$n1000, range_x = range_num
)

par(mfrow = c(1, 1))
```


</br>



## Show that this is a Distribution


</br>



## Derive the Moment Generating Function


</br>



## Method of Moments Estimates from Observed Data
Let's generate some random data...


### $\mathbb{E}[k]$


### $\mathbb{E}[k^2]$ and $\text{Var}[k]$


### Solving the System


</br>



## Maximum Likelihood Estimators


</br>



## Exercises


